### ISSUE TITLE
W10D2 (2일차) - 

### ISSUE THREAD

**Issue by hanjo8813** [ham-study/cs-study-for-interview#198]
- 구조패턴
   - 어댑터
- 행위패턴
   - 옵저버
   - 템플릿 메소드

**Comment by hanjo8813** [comment]
### Spring

- spring 동작원리
   - IoC
   - DI
   - servlet
   -

**Comment by sunH0** [comment]
- Spring Security
- My batis
- Annotation
  - @Service,@Controller,@Component 차이 
  - Bean/Component 
- [MVC1 vs MVC2]
- Maven vs Gradle
- 세션과 쿠키의 차이점
- AJAX
- 플랫폼, 프레임워크, 라이브러리 차이점
-  Spring Framework에서 사용되는 디자인 패턴
- 반응 형 프로그래밍
- Git을 쓰는 이유와 깃과 깃허브의 차이점

**Comment by GetMapping** [comment]
- 어댑터 패턴에 대해서 설명해주세요.
- 어댑터 패턴을 사용해 보신적 있으신가요?
- 어댑터 패턴의 사용 예시를 알고계신가요?
- 상속과 합성의 차이점이 무엇인가요?
- 어댑터 패턴은 왜 사용하나요?
- 행위 패턴 중 아시는 패턴에 대해 말씀해주시겠어요?
- 옵저버 패턴에 대해서 설명해주세요.
- 옵저버 패턴을 사용해 보신적 있으신가요?
- 옵저버 패턴이 느슨한 결합인 이유가 무엇인가요?
