### ISSUE TITLE
W10D5 (2일차) - Spring 기초 1

### ISSUE THREAD

**Issue by hanjo8813** [ham-study/cs-study-for-interview#204]
- Spring vs Spring MVC vs Spring Boot
      - MVC1 vs MVC2
   - dispatcher servlet

**Comment by GetMapping** [comment]
- 스프링 프레임 워크를 사용해 보신 적 있으신가요? 사용하신 이유가 있나요?
- 스프링 프레임 워크에 대해서 설명해주세요.
- Spring과 SpringBoot의 차이점에 대해 설명해주세요.
- Spring과 SpringMVC의 차이점에 대해 설명해주세요.
- MVC1과 MVC2의 차이점에 대해 설명해주세요.
- SpringMVC 구조에서 http 요청이 들어왔을때 어떻게 동작하나요?
- DispatcherServlet이 어떻게 동작하나요?
