### ISSUE TITLE
W11D3 (5일차) - interceptor

### ISSUE THREAD

**Issue by hanjo8813** [ham-study/cs-study-for-interview#207]
- interceptor 
   - filter와 차이점
- Spring 전체 동작과정 총정리

**Comment by GetMapping** [comment]
- Filter와 Interceptor가 필요한 이유가 무엇인가요?
- Filter와 Interceptor의 차이점은 무엇인가요?
- Interceptor와 AOP의 차이가 무엇인가요?
- Filter의 동작 방식에 대해서 설명해주세요.
- 전체적인 동작 과정을 설명해주세요.
