### ISSUE TITLE
W12D4 (10일차) - Spring Test

### ISSUE THREAD

**Issue by hanjo8813** [ham-study/cs-study-for-interview#228]
- DDD, TDD
- 테스트 
   - Junit4 vs Junit5
   - 단위, 통합, 인수 테스트
   - stub, mock
   - SpringBoot 계층별 테스트 방법
   - 테스트 커버리지 (JACOCO)

**Comment by sunH0** [comment]
- TDD를 사용해 프로젝트 개발을 해보신 적이 있으시나요? 없다면 왜 사용하시지 않으셨죠?
- TDD를 어떠한 경우에 사용하면 좋을까요?
- Junit에 대해 아시나요? 아신다면 언제 사용하셨죠?
- Junit5를 사용하신 이유가 있으시나요?
- 테스트 종류에 대해 설명해주세요. 이중 어떤 종류를 사용해보셨나요?
- 계층간 테스트 코드는 어떻게 작성하셨나요?
- stub과 mock의 차이에 대해 아시나요?
- JACOCO를 사용해보셨던데 왜 사용하셨나요?
