### ISSUE TITLE
기타주제

### ISSUE THREAD

**Issue by hanjo8813** [ham-study/cs-study-for-interview#232]
CS 필수 카테고리를 모두 끝내고 부족했던 키워드를 공부해봐요
추가하고 싶은 키워드가 있다면 자유롭게 추가해주세요  

- **--- 1일차 ---**
- 어노테이션
- POJO
- jar vs war
- Maven vs Gradle
- **--- 2일차 ---**
- Spring Security
- **--- 3일차 ---**
- Spring Resolver
- Spring Async
- 플랫폼, 프레임워크, 라이브러리 차이점
- Git을 쓰는 이유와 깃과 깃허브의 차이점

**Comment by hanjo8813** [comment]
- 어노테이션이 무엇인가요?
   - 어노테이션의 기능에 대해 설명해주세요
   - 어노테이션의 장점을 설명해주세요
   - 어노테이션 직접 만들어서 사용해보신적 있으신가요? 
   - 따로 메소드를 만들어도 되는데 왜 어노테이션을 사용하셨나요?
- POJO가 무엇인가요?
- jar와 war 차이점에 대해 알려주세요
- Maven과 Gradle 차이점에 대해 알려주세요

**Comment by hanjo8813** [comment]
- 프로젝트에서 인증/인가를 사용하셨나요?
   - 어떤 기술을 사용하셨나요?
      - 세션 기반인가요 토큰 기반인가요? -> 자세히 설명해주세요
   - 인증, 인가에 대해서 설명해주세요
- Spring Security의 동작원리에 대해 설명해주세요
-

**Comment by sunH0** [comment]
- 프레임워크와 라이브러리의 차이점은?
- 프레임워크를 사용하였을 때 좋았던 점?
- 깃과 깃허브를 사용해보셨을 때 어떠한 장점이 있으셨나요?
- 실제로 깃허브를 협업 관점에서 어떻게 사용하셨나요?
- api 가 무엇인가요?
- 깃과 깃허브는 뭐가 다르나요?
- spring에서 resolver를 사용해 보셨나요?
- ArgumentResolver 동작원리에 대해 아시나요?
- 스프링 프로젝트에서 비동기 처리를 적용해보신 적이 있으신가요?
- @async 어노테이션을 private 메소드에 적용 가능하나요?
